/** 用户免登录url */
export const AUTO_LOGIN_URL='/auto/login'
/** 获取验证码url */
export const USER_CODE_URL='/phone/code'
/** 验证码登录url */
export const PHONE_LOGIN_URL='/login/phone'
/** 账户密码登录url */
export const ACCOUNT_LOGIN_URL='/user/login'
/** 获取协议url */
export const SUGGEST_INFO_URL='/suggest/info'
/** 用户注册url */
export const USER_REGISTER_URL='/user/register'
/** 修改密码接口url */
export const UPDATE_PASSWORD_URL='/update/password'
/** 首页分类数据url */
export const HOME_TYPES_URL='/home/types'
/** 首页推荐列表数据url */
export const HOME_RECOMMEND_URL='/home/recommend'
/** listtype数据 */
export const LIST_TYPE_URL='/list/types'
/** 不同类型商品推荐 */
export const RECOMMEND_TYPE_URL='/recommend/type'
/** 详细类型商品推荐 */
export const RECOMMEND_DETAILTYPE_URL='/recommend/detailtype'